from __future__ import annotations

from pathlib import Path

import pytest

from aetext.classification import (
    ClassificationError,
    apply_classification_plan,
    build_classification_plan,
    check_project_classification,
)


def _project(root: Path, name: str, *, category_macro: str = "FS_CATEGORY") -> Path:
    source = root / name
    win = source / "Win"
    win.mkdir(parents=True)
    project = win / f"{name}.vcxproj"
    project.write_text(
        f"""<?xml version=\"1.0\" encoding=\"utf-8\"?>
<Project xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
  <ItemGroup>
    <ClInclude Include=\"..\\Fs_Target.h\" />
    <CustomBuild Include=\"..\\{name}PiPL.r\" />
  </ItemGroup>
</Project>
""",
        encoding="utf-8",
    )
    (source / f"{name}PiPL.r").write_text(
        f'#include "Fs_Target.h"\nCategory {{ {category_macro} }}\n', encoding="utf-8"
    )
    (source / "Fs_Target.h").write_text(
        f'//#define {category_macro} "Wrong"\n#define {category_macro} "NF\'s Plugins-Filter"\n',
        encoding="utf-8",
    )
    return project


def _solution(root: Path, projects: list[Path]) -> None:
    entries = "\n".join(
        f'    <Project Path="{path.relative_to(root).as_posix()}" />' for path in projects
    )
    (root / "F's PluginsProjects.slnx").write_text(
        f"""<Solution>
  <Configurations>
    <Platform Name=\"x64\" />
  </Configurations>
  <Folder Name=\"/Old/\">
{entries}
  </Folder>
</Solution>
""",
        encoding="utf-8",
    )


def _catalog(root: Path, relative: str) -> Path:
    path = root / "_localization" / "catalog" / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('{"schemaVersion": 1, "translations": {}}\n', encoding="utf-8")
    return path


def test_plan_derives_category_role_isolation_and_generated_files(tmp_path: Path) -> None:
    alpha = _project(tmp_path, "Alpha")
    fake = _project(tmp_path, "Fake", category_macro="NFS_CATEGORY")
    _catalog(tmp_path, "NF's Plugins-Filter/Alpha.json")
    _catalog(tmp_path, "NF's Plugins-Filter/(fake)/Fake.json")
    _solution(tmp_path, [alpha, fake])

    plan = build_classification_plan(tmp_path)

    assert [(item.name, item.role, item.category, item.isolation) for item in plan.projects] == [
        ("Alpha", "Production", "NF's Plugins-Filter", ""),
        ("Fake", "Production", "NF's Plugins-Filter", "(fake)"),
    ]
    assert "Generated by `uv run aetext sync-classification`" in plan.plugin_map_text
    assert "<FsOutputIsolation>(fake)</FsOutputIsolation>" in plan.plugin_map_text
    assert '<Folder Name="/NF\'s Plugins-Filter/(fake)/">' in plan.solution_text


def test_nfs_skeleton_still_uses_its_actual_nfs_category(tmp_path: Path) -> None:
    project = _project(tmp_path, "NFsSkelton", category_macro="NFS_CATEGORY")
    _catalog(tmp_path, "(Templates)/NFsSkelton.json")
    _solution(tmp_path, [project])

    item = build_classification_plan(tmp_path).projects[0]

    assert (item.name, item.role, item.category) == (
        "NFsSkelton",
        "Templates",
        "NF's Plugins-Filter",
    )


def test_plan_reports_and_apply_repairs_all_derived_outputs_idempotently(tmp_path: Path) -> None:
    project = _project(tmp_path, "Alpha")
    old_catalog = _catalog(tmp_path, "Wrong/Alpha.json")
    _solution(tmp_path, [project])
    (tmp_path / "Directory.Build.PluginMap.props").write_text("stale\n", encoding="utf-8")

    plan = build_classification_plan(tmp_path)

    assert plan.changed
    assert plan.catalog_moves == [
        (
            old_catalog.resolve(),
            (tmp_path / "_localization/catalog/NF's Plugins-Filter/Alpha.json").resolve(),
        )
    ]
    apply_classification_plan(plan)
    second = build_classification_plan(tmp_path)
    assert not second.changed
    assert second.catalog_moves == []


def test_plan_rejects_missing_or_multiple_category_definitions(tmp_path: Path) -> None:
    project = _project(tmp_path, "Alpha")
    target = tmp_path / "Alpha" / "Fs_Target.h"
    _catalog(tmp_path, "NF's Plugins-Filter/Alpha.json")
    _solution(tmp_path, [project])

    target.write_text("// no category\n", encoding="utf-8")
    with pytest.raises(ClassificationError, match="exactly one active definition"):
        build_classification_plan(tmp_path)

    target.write_text(
        '#define FS_CATEGORY "NF\'s Plugins-Filter"\n#define FS_CATEGORY "NF\'s Plugins-Cell"\n',
        encoding="utf-8",
    )
    with pytest.raises(ClassificationError, match="exactly one active definition"):
        build_classification_plan(tmp_path)


def test_plan_rejects_multiple_catalogs_for_one_project(tmp_path: Path) -> None:
    project = _project(tmp_path, "Alpha")
    _catalog(tmp_path, "NF's Plugins-Filter/Alpha.json")
    _catalog(tmp_path, "Elsewhere/Alpha.json")
    _solution(tmp_path, [project])

    with pytest.raises(ClassificationError, match="multiple catalogs"):
        build_classification_plan(tmp_path)


def test_support_role_does_not_require_an_effect_pipl_category(tmp_path: Path) -> None:
    source = tmp_path / "Settings"
    win = source / "Win"
    win.mkdir(parents=True)
    project = win / "FsLanguageSettings.vcxproj"
    catalog = _catalog(tmp_path, "_Support/Settings.json")
    project.write_text(
        """<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="..\\..\\_localization\\catalog\\_Support\\Settings.json" />
  </ItemGroup>
</Project>
""",
        encoding="utf-8",
    )
    _solution(tmp_path, [project])

    plan = build_classification_plan(tmp_path)

    assert len(plan.projects) == 1
    item = plan.projects[0]
    assert (item.name, item.role, item.category) == (
        "FsLanguageSettings",
        "Support",
        "",
    )
    assert item.expected_catalog_path == catalog.resolve()
    assert item.solution_folder == "/_Support/"
    assert "<FsAeCategory>" not in plan.plugin_map_text


def test_non_support_project_still_requires_one_actual_pipl_input(tmp_path: Path) -> None:
    project = _project(tmp_path, "Alpha")
    _catalog(tmp_path, "NF's Plugins-Filter/Alpha.json")
    _solution(tmp_path, [project])
    project.write_text(
        """<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup><ClInclude Include="..\\Fs_Target.h" /></ItemGroup>
</Project>
""",
        encoding="utf-8",
    )

    with pytest.raises(ClassificationError, match="exactly one existing PiPL CustomBuild"):
        build_classification_plan(tmp_path)


def test_project_gate_rejects_a_manual_plugin_map_edit(tmp_path: Path) -> None:
    project = _project(tmp_path, "Alpha")
    _catalog(tmp_path, "NF's Plugins-Filter/Alpha.json")
    _solution(tmp_path, [project])
    plan = build_classification_plan(tmp_path)
    apply_classification_plan(plan)
    check_project_classification(tmp_path, project)

    plan.plugin_map_path.write_text(
        plan.plugin_map_text.replace("NF's Plugins-Filter", "NF's Plugins-Cell"),
        encoding="utf-8",
    )
    with pytest.raises(ClassificationError, match="PluginMap is stale"):
        check_project_classification(tmp_path, project)
